
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-role
rules:
  - apiGroups:
      - 'apps'
    resources:
      - '*'
    verbs:
      - '*'
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: plugin-k8s-role-binding
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: k8s-role
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: myweb
  namespace: pipeline-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: eromski/mybuildnumber:<TAG>
        imagePullPolicy: Always
        name: myweb

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb
  name: myweb
  namespace: pipeline-demo
spec:
  ports:
  - nodePort: 32323
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myweb
  type: NodePort
